let firstNumber = 27;
let secondNumber = 18;
console.log(firstNumber, secondNumber);
let tempNumber = secondNumber;
secondNumber = firstNumber;
firstNumber = tempNumber;
console.log(firstNumber, secondNumber);
firstNumber = 27;
secondNumber = 18;
console.log(firstNumber, secondNumber);
[firstNumber, secondNumber] = [secondNumber, firstNumber];
console.log(firstNumber, secondNumber);
firstNumber = 27;
secondNumber = 18;
console.log(firstNumber, secondNumber);
let sortArray = [firstNumber, secondNumber];
firstNumber = sortArray[1];
secondNumber = sortArray[0];
console.log(firstNumber, secondNumber);
